FROM node:24.0.2-alpine3.20@sha256:3ce0ee44c2aa0ef436a24241ce25c590ae457b915ef840b1a423653419e8fc3e

RUN apk add --no-cache \
        gifsicle \
        ffmpeg \
        imagemagick

# install gifify
RUN npm i -g gifify

# run gifify in /data (requires user to mount their source folder in /data)
WORKDIR /data
ENTRYPOINT ["gifify"]
