FROM node:23.9.0-alpine3.20@sha256:bd7fcef9f2e75a89181d42c3a9e9283563ee10f1ba416219871cd33d6c6d5cc5

RUN apk add --no-cache \
        gifsicle \
        ffmpeg \
        imagemagick

# install gifify
RUN npm i -g gifify

# run gifify in /data (requires user to mount their source folder in /data)
WORKDIR /data
ENTRYPOINT ["gifify"]
