FROM node:23.9.0-bookworm-slim@sha256:dcacc1ee3b03a497c2096b0084d3a67b856e777b55ffccfcc76bcdab9cc65906

RUN apt-get update && \
    apt-get install -y \
        gifsicle \
        ffmpeg \
        imagemagick

# install gifify
RUN npm i -g gifify

# run gifify in /data (requires user to mount their source folder in /data)
WORKDIR /data
ENTRYPOINT ["gifify"]
