FROM node:24.0.2-bookworm-slim@sha256:952e289d462be9b5b9e375718f08ed8445082d22d088a0be74ae0251d4fd91d7

RUN apt-get update && \
    apt-get install -y \
        gifsicle \
        ffmpeg \
        imagemagick

# install gifify
RUN npm i -g gifify

# run gifify in /data (requires user to mount their source folder in /data)
WORKDIR /data
ENTRYPOINT ["gifify"]
